### ISSUE TITLE
Inserting archives and sets breaks some sounds

### ISSUE THREAD

**Issue by thane98** [thane98/BCSAR-View#1]
After inserting an archive or set into FE14's BCSAR, some sound effects (possibly sequences?) stop playing.

**Comment by novakirby** [comment]
Inserting wave sound would cause ItemId of sequences moved backward, and hence breaks reference in group file ("GROUP_COMMON"). One could (hopefully) fix this by modifying first three ItemId in the group manually.

**Comment by thane98** [comment]
Yeah, that was it. Should be fixed with ea07d491a607cb6817d3cdb4eaff293a038defcb. Thanks for finding that!
